Repository simonmichael/hledger, pull requests merged in 2018-05, with the labels that each got.

#764 Fix doctest error.
  hledger-lib/Hledger/Read/Common.hs
Labels: A BUG, in progress, journal

#767 GHC 8.0 compatibility
  hledger-lib/Hledger/Data/Dates.hs
  hledger-lib/Hledger/Read/Common.hs
  hledger-lib/hledger-lib.cabal
  hledger-lib/package.yaml
  hledger/Hledger/Cli/Utils.hs
  stack-ghc8.0.yaml
Labels: in progress

#773 lib: fix performance regression introduced in 30ae9914
  hledger-lib/Hledger/Read/Common.hs
Labels: in progress, journal, performance

#780 lib: fix parsing of amounts with a whitespace digits separator
  hledger-lib/Hledger/Read/Common.hs
  tests/journal/amounts-and-commodities.test
Labels: in progress

#782 lib: fix issue where spaces were allowed as decimal points
  hledger-lib/Hledger/Read/Common.hs
  tests/journal/amounts-and-commodities.test
Labels: in progress

#788 More work on the parser
  hledger-lib/Hledger/Read/Common.hs
Labels: in progress
