Repository simonmichael/hledger, pull requests merged in 2019-12, with the labels that each got.

#1146 Add a basic example of rule parsing for the output of csb2format.
  examples/csv/csb43.csv
  examples/csv/csb43.csv.rules
Labels: csv, docs

#1140 fix parsing of < and > in add-on commands (#457)
  hledger-lib/Hledger/Utils/String.hs
  tests/addons/addons.test
  tests/rewrite.test
Labels: cli

#1151 Change the '<' command to go back one step during addition
  hledger/Hledger/Cli/Commands/Add.hs
  hledger/Hledger/Cli/Commands/Add.md
  hledger/Hledger/Cli/Commands/Add.txt
  hledger/hledger.1
  hledger/hledger.info
  hledger/hledger.txt
Labels: ui

#1138 Simplify date comparison code.
  hledger-lib/Hledger/Query.hs
Labels: needs:discussion
