Repository simonmichael/hledger, pull requests merged in 2020-06, with the labels that each got.

#1257 ui: fix regression in 'F' (fixes #1255)
  hledger-ui/Hledger/UI/UIState.hs
Labels: ui

#1258 cli: changes to "hledger print -O csv" output
  hledger/Hledger/Cli/Commands/Print.hs
Labels: csv

#1263 lib: Add fortnightly as a synonym for biweekly.
  hledger-lib/Hledger/Data/Dates.hs
  hledger/hledger.1
  hledger/hledger.m4.md
Labels: A WISH, queries
