Repository simonmichael/hledger, pull requests merged in 2021-07, with the labels that each got.

#1576 Don't write debug.log when reloading the journal in hledger-ui's transaction screen
  hledger-lib/Hledger/Utils/Debug.hs
  hledger-ui/Hledger/UI/UIState.hs
Labels: A BUG, ui

#1578 lib,cli: No longer strip prices in journalApplyValuationFromOptsWith …
  hledger-lib/Hledger/Reports/MultiBalanceReport.hs
  hledger-lib/Hledger/Reports/ReportOptions.hs
  hledger/Hledger/Cli/Commands/Balance.hs
  hledger/Hledger/Cli/Commands/Close.hs
  hledger/Hledger/Cli/Commands/Register.hs
Labels: ui

#1587 lib: Make sure automatic postings generated from postings with more t…
  hledger-lib/Hledger/Data/TransactionModifier.hs
  hledger/test/journal/auto-postings.test
Labels: journal

#1571 Static builds for Linux on x64 (amd64) and arm32v7 architectures
  .github/workflows/static-linux-arm32v7.yml
  .github/workflows/static-linux.yml
  docker-static-arm32v7/Dockerfile
Labels: A WISH, packaging, platform: docker, platform: linux, platform: nextcloud, tools

#1588 In hledger-ui TransactionScreen, set the current transaction based on RegisterScreen.
  hledger-ui/Hledger/UI/RegisterScreen.hs
  hledger-ui/Hledger/UI/TransactionScreen.hs
  hledger-ui/Hledger/UI/UIState.hs
Labels: ui

#1595 ;imp: added systemd and nginx files to examples dir
  examples/systemd/hledger-web.service
  examples/systemd/hledger.nginx
  examples/systemd/readme.md
Labels: A WISH, docs

#1564 more useful sort order for multi-commodity MixedAmounts: treat missing commodities as 0
  hledger-lib/Hledger/Data/Amount.hs
  hledger-lib/Hledger/Data/Posting.hs
  hledger-lib/Hledger/Data/Types.hs
  hledger/Hledger/Cli/Commands/Balance.md
  hledger/test/balance/sorting.test
Labels: A WISH, journal

#1616 Provide more verbose advise on complex quoting use-cases highlighted in #1609
  hledger/Hledger/Cli/Commands/Roi.md
  hledger/hledger.m4.md
Labels: roi
