Repository simonmichael/hledger, pull requests merged in 2021-01, with the labels that each got.

#1448 ;doc: adjust traditional top level accounts
  hledger/hledger.m4.md
Labels: docs

#1454 lib: better message when roi fails to value commodity, fixes #1446
  hledger/Hledger/Cli/Commands/Roi.hs
  hledger/test/roi.test
Labels: roi

#1434 make csvtest.sh script POSIX and shellchecked
  hledger/test/csvtest.sh
Labels: platform: freebsd, platform: mac, tools
