Repository simonmichael/hledger, pull requests merged in 2021-06, with the labels that each got.

#1551 lib: Do not attempt to infer price when amounts have the same sign.
  hledger-lib/Hledger/Data/Transaction.hs
  hledger/test/journal/auto-postings.test
  hledger/test/journal/parse-errors.test
Labels: needs:review

#1543 cli,ui: Include full binary name and git hash in program version.
  hledger-ui/Hledger/UI/UIOptions.hs
  hledger-web/Hledger/Web/WebOptions.hs
  hledger/Hledger/Cli/Main.hs
  hledger/Hledger/Cli/Version.hs
  hledger/hledger.cabal
  hledger/package.yaml
Labels: A WISH, needs:changes

#1544 Add option to disable automatic price inferral in unbalanced multicommodity transactions.
  hledger-lib/Hledger/Data/Journal.hs
  hledger-lib/Hledger/Data/Transaction.hs
  hledger-lib/Hledger/Read/Common.hs
  hledger-lib/Hledger/Read/CsvReader.hs
  hledger-lib/Hledger/Reports/BalanceReport.hs
  hledger-lib/Hledger/Reports/BudgetReport.hs
  hledger-ui/Hledger/UI/AccountsScreen.hs
  hledger-ui/Hledger/UI/ErrorScreen.hs
  hledger-ui/Hledger/UI/RegisterScreen.hs
  hledger-ui/Hledger/UI/TransactionScreen.hs
  hledger-ui/Hledger/UI/UIState.hs
  hledger-web/Hledger/Web/Widget/AddForm.hs
  hledger/Hledger/Cli/Commands/Add.hs
  hledger/Hledger/Cli/Commands/Balance.hs
  hledger/Hledger/Cli/Commands/Check.hs
  hledger/Hledger/Cli/Commands/Check.md
  hledger/Hledger/Cli/Commands/Diff.hs
  hledger/Hledger/Cli/Commands/Import.hs
  hledger/Hledger/Cli/Utils.hs
  hledger/test/check-balancednoautoconversion.test
  hledger/test/journal/transaction-prices.test
Labels: A WISH

#1574 Improve editor support
  hledger-ui/Hledger/UI/Editor.hs
Labels: ui
