Repository simonmichael/hledger, pull requests merged in 2021-08, with the labels that each got.

#1623 Implement gain report for balance reports.
  hledger-lib/Hledger/Data/Valuation.hs
  hledger-lib/Hledger/Reports/MultiBalanceReport.hs
  hledger-lib/Hledger/Reports/ReportOptions.hs
  hledger/Hledger/Cli/Commands/Balance.hs
  hledger/Hledger/Cli/Commands/Balance.md
  hledger/Hledger/Cli/CompoundBalanceCommand.hs
  hledger/test/journal/gain.test
Labels: A WISH, balance, investment, needs:review

#1632 New periodic expressions for every weekday et al
  hledger-lib/Hledger/Data.hs
  hledger-lib/Hledger/Data/Dates.hs
  hledger-lib/Hledger/Data/Types.hs
  hledger/hledger.m4.md
  hledger/test/forecast.test
Labels: A WISH, cli, journal, needs:changes, periodexpressions

#1664 Fix cmdline example typo, f- should be -f-
  hledger/hledger.1
  hledger/hledger.info
  hledger/hledger.m4.md
  hledger/hledger.txt
Labels: A BUG, docs, cli, queries

#1668 fix: ui: Make sure RegisterScreen (and consequently TransactionScreen)
  hledger-ui/Hledger/UI/AccountsScreen.hs
  hledger-ui/Hledger/UI/RegisterScreen.hs
  hledger-ui/Hledger/UI/UIUtils.hs
Labels: ui
